openapi: '3.0.3'
info:
  title: RideShare
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
